import { useRef, useState } from 'react'
import { Link } from 'react-router-dom'
import styles from './CreationSuccess.module.css'

interface CopyableUrlProps {
  id: string
  label: string
  url: string
}

/**
 * A read-only URL field with an accessible copy button. Copy confirmation
 * is communicated via visible text in an `aria-live` region — never by
 * color or icon alone (this slice's accessibility requirements) — and
 * reverts after a few seconds so a second copy can be confirmed again.
 *
 * When `navigator.clipboard.writeText` isn't available or rejects (common
 * on non-secure origins and some mobile browsers), this falls back to
 * focusing and fully selecting the field via the standard input selection
 * APIs, so the follow-up guidance is "tap the OS Copy action" rather than
 * "manually drag the selection handles."
 */
export function CopyableUrl({ id, label, url }: CopyableUrlProps) {
  const [copyState, setCopyState] = useState<'idle' | 'copied' | 'failed'>(
    'idle',
  )
  const inputRef = useRef<HTMLInputElement>(null)

  function selectField() {
    const input = inputRef.current
    if (!input) {
      return
    }
    input.focus()
    // select() alone covers most browsers; the explicit range is a
    // defensive extra for mobile browsers that only reliably show
    // selection handles across the whole value when given one directly.
    input.select()
    input.setSelectionRange(0, input.value.length)
  }

  async function handleCopy() {
    if (navigator.clipboard?.writeText) {
      try {
        await navigator.clipboard.writeText(url)
        setCopyState('copied')
        return
      } catch {
        // Fall through to the selection fallback below.
      }
    }
    setCopyState('failed')
    selectField()
  }

  return (
    <div className={styles.urlBlock}>
      <label htmlFor={id}>{label}</label>
      <div className={styles.urlRow}>
        <input
          id={id}
          ref={inputRef}
          className={styles.urlInput}
          type="text"
          readOnly
          value={url}
          onFocus={(event) => event.currentTarget.select()}
        />
        <button
          type="button"
          className="button button--secondary"
          onClick={() => void handleCopy()}
        >
          Copy
        </button>
      </div>
      <p role="status" className={styles.copyStatus}>
        {copyState === 'copied'
          ? `${label} copied to clipboard.`
          : copyState === 'failed'
            ? 'Could not copy automatically — select the text above and copy it manually.'
            : ''}
      </p>
    </div>
  )
}

export interface CreationSuccessProps {
  troveId: string
  publicUrl: string
  managementUrl: string
  /** Shows an extra warning specific to Private mode: unlike the
   * management link (which can at least be regenerated by... nothing —
   * neither can be recovered, but the share link is *also* the only
   * decryption capability, docs/PRIVATE_ENVELOPE.md §15, not just a
   * bookmark). Defaults to `'standard'` so existing callers are
   * unaffected. */
  mode?: 'standard' | 'private'
  /** Invoked when "Create another trove" is activated. This is a plain
   * button rather than a `Link to="/create"` because the caller (this
   * page's own route is already `/create`) needs to clear its own
   * `created` state — a same-path `Link` is a no-op navigation that
   * leaves this component mounted with its stale success state, which is
   * what made the button appear to do nothing. */
  onCreateAnother: () => void
}

/**
 * Shown exactly once, immediately after a successful creation
 * (docs/V0.1_SPEC.md §2, step 4/5). Both URLs — and the management secret
 * embedded in `managementUrl`'s fragment — exist only in this component's
 * (and its caller's) in-memory React state for the lifetime of this page
 * view. Nothing here writes to `localStorage`/`sessionStorage`/cookies,
 * and navigating away loses this exact rendering permanently — there is
 * no recovery mechanism, which is the point of the warning below.
 */
export function CreationSuccess({
  troveId,
  publicUrl,
  managementUrl,
  mode = 'standard',
  onCreateAnother,
}: CreationSuccessProps) {
  return (
    <div className="page">
      <h1>Your trove is ready</h1>

      <div className={styles.warning} role="alert">
        <p>
          <strong>Save the management link below now.</strong> Anyone who has it
          can edit or delete this trove — treat it like a password.
        </p>
        <p>
          Vultrove cannot recover this link if you lose it. There is no account,
          and no "forgot my link" option.
        </p>
        {mode === 'private' ? (
          <p>
            <strong>
              The share link below is also required to decrypt this trove.
            </strong>{' '}
            It is not just a bookmark — the part after "#" never leaves your
            browser and is never stored by Vultrove. If you lose it, this
            trove's contents are permanently unrecoverable, by you or by
            Vultrove.
          </p>
        ) : null}
      </div>

      <CopyableUrl id="public-url" label="Share link" url={publicUrl} />
      <CopyableUrl
        id="management-url"
        label="Management link"
        url={managementUrl}
      />

      <div className={styles.actions}>
        <Link to={`/c/${encodeURIComponent(troveId)}`} className="button">
          View your trove
        </Link>
        <button
          type="button"
          className="button button--secondary"
          onClick={onCreateAnother}
        >
          Create another trove
        </button>
      </div>
    </div>
  )
}
